### PR TITLE
Updated list of AiiDA powered research papers

### PR DESCRIPTION
**Pull request by khsrali**
I did a manual search to make this updated list of papers powered by AiiDA. 
The idea is to have this PR ready to go at the same time as we send questionnaire, so that people can add their research paper to this page, if not listed. (this is probable, since my manual approach was pessimistic)

### CODE REVIEW

**Comment by sphuber** [comment]
How did you perform the search exactly? Did you just get _any_ paper that cites the AiiDA paper? And which paper, the original from 2016, or also the [2020](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=5IvveJ4AAAAJ&citation_for_view=5IvveJ4AAAAJ:qjMakFHDy7sC) one? What about the [ACWF v1.0](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=5IvveJ4AAAAJ&citation_for_view=5IvveJ4AAAAJ:ufrVoPGSRksC) and [ACWF v2.0](https://www.nature.com/articles/s42254-023-00655-3)?

**Comment by khsrali** [comment]
> How did you perform the search exactly? Did you just get _any_ paper that cites the AiiDA paper? And which paper, the original from 2016, or also the [2020](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=5IvveJ4AAAAJ&citation_for_view=5IvveJ4AAAAJ:qjMakFHDy7sC) one? What about the [ACWF v1.0](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=5IvveJ4AAAAJ&citation_for_view=5IvveJ4AAAAJ:ufrVoPGSRksC) and [ACWF v2.0](https://www.nature.com/articles/s42254-023-00655-3)?

I fetch all papers citing at least either 
Main paper: [S.P. Huber et al., Scientific Data 7, 300 (2020)](https://doi.org/10.1038/s41597-020-00638-4)
AiiDA engine: [M. Uhrin et al., Comp. Mat. Sci. 187 (2021)](https://doi.org/10.1016/j.commatsci.2020.110086)

And check them one by one, discarded those which don't actually use aiida for *research*.

The list is accurate but not complete, for instance it doesn't include those aiida powered research paper citing *only* the
First paper, ADES model: [G. Pizzi et al. Comp. Mat. Sci. 111, 218-230 (2016)](https://dx.doi.org/10.1016/j.commatsci.2015.09.013)

That's why at some point they got too many to check manually, so I made a PR of those we are sure, and hopefully will catch the rest by sending the questionnaire.

**Comment by sphuber** [comment]
Thanks a lot @khsrali . That makes sense. But maybe it would be useful to add a disclaimer saying that these are curated manually and so that the list is not exhaustive.

Also, probably have to update this comment:
```
list of publications containing calculations powered by AiiDA, selected from the [citations of the AiiDA paper](https://scholar.google.com/scholar?cites=10268089832296963062&as_sdt=2005&sciodt=0,5&hl=en).
```
to include all the papers that you include in the search.

Would it be possible to add the ACWF v1.0 paper perhaps? It has 20 citations currently, but might have relevant research papers

**Comment by sphuber** [comment]
> For this and the picture, honestly, maybe it's more convenient to wait until we collect responses from the questionnaire.

Just to be clear, what I meant was to add the engine paper, because you said the selected papers also contain those that cite the engine paper.

**Comment by khsrali** [comment]
Hi @sphuber , I added the disclaimer. I intentionally repeated it under each relevant section. 
Later, after sending off the questionnaire, we can slowly complete the list.

**Comment by sphuber** [comment]
Thanks @khsrali . Changes look good, but the CI is failing. Don't understand why this is happening  now, but it seems that the Python version we are using is no longer compatible with `pydata-sphinx-theme`. I will quickly fix that and then we can merge this

**Comment by sphuber** [comment]
https://github.com/aiidateam/aiida-website/pull/63

**Review by sphuber — APPROVED** [review]
Thanks a lot @khsrali

**Comment by khsrali** [comment]
Super! Thanks a lot for the quick action @sphuber

**Pull request merged**
